#!/bin/bash

if [ -z $1 ]; then
   echo "Usage: maintenance (on|off|sleep NUM VALUE)"
   echo ""
   echo "Example: "
   echo ""
   echo "maintenance on - Switches on Maintenance Mode"
   echo "maintenance off - Switches off Maintenance Mode"
   echo "maintenance sleep - Switches on Maintenance Mode temporarily for 15 minutes"
   echo "maintenance sleep 10 min - Switches on Maintenance Mode temporarily for 10 min"
   echo ""
   echo "Valid VALUE is seconds (sec, secs), minutes (min, mins) , hours (hour, hr) , days (day)"
   exit
fi

case "$1" in
     "on" | "ON" | "true" | "TRUE" )
	    mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.orig
        mv /etc/nginx/conf.d/maintenance.conf.maint /etc/nginx/conf.d/maintenance.conf
        nginx -s reload
        echo 'Maintenance Mode Activated'
     ;;	
     "off" | "OFF" | "false" | "FALSE" )
	    mv /etc/nginx/conf.d/default.conf.orig /etc/nginx/conf.d/default.conf
        mv /etc/nginx/conf.d/maintenance.conf /etc/nginx/conf.d/maintenance.conf.maint
        nginx -s reload
        echo 'Maintenance Mode Deactivated'
     ;;
     "sleep" | "SLEEP" | "temp" | "TEMP" )
	    mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.orig
        mv /etc/nginx/conf.d/maintenance.conf.maint /etc/nginx/conf.d/maintenance.conf
        nginx -s reload
        if [ -z $2 ]; then
            SLEEPNUM="15"
            SLEEPCALC=$((15 * 60))
        fi

        if [ -z $3 ]; then
            set -- "${@:1:2}" "min"
        fi

        case "$3" in
            "min" | "minutes" | "MIN" | "MINUTES" )
                SLEEPCALC=$(($2 * 60))
                SLEEPDESC="minutes"
             ;;
             "seconds" | "secs" | "sec" | "SECONDS" | "SECS" | "SEC" )
                SLEEPCALC=$(($2 * 1))
                SLEEPDESC="seconds"
             ;;
              "hour" | "hours" | "hr" | "hrs" | "HOUR" | "HOURS" | "HRS" )
                SLEEPCALC=$(($2 * 3600))
                SLEEPDESC="hour(s)"
             ;;
             "day" | "days" | "DAY" | "DAYS" )
                SLEEPCALC=$(($2 * 86400))
                SLEEPDESC="day(s)"
             ;;
        esac     

        echo 'Maintenance Mode Temporarily Activated for '$SLEEPNUM' '$SLEEPDESC
        sleep $SLEEPCALC
        mv /etc/nginx/conf.d/default.conf.orig /etc/nginx/conf.d/default.conf 
        mv /etc/nginx/conf.d/maintenance.conf /etc/nginx/conf.d/maintenance.conf.maint
        nginx -s reload
        echo 'Maintenance Mode Deactivated'
     ;;
esac
