source_directories:
    - /mnt/source/
repositories:
    - path: ssh://to-your-backup-server:22/./freescout
      label: rsync

keep_hourly: 24
keep_daily: 7
keep_weekly: 4
keep_monthly: 6

mysql_databases:
    - name: freescout
      hostname: freescout-db
      username: freescout
      password: freescout
      options: --default-character-set=utf8mb4
