#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/init-10-nginx ]
do
  sleep 1
done

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
    set -x
fi

### Set Defaults
  APC_SHM_SIZE=${APC_SHM_SIZE:-"128M"}
  OPCACHE_MEM_SIZE=${OPCODE_MEM_SIZE:-"128"}
  PHP_LOG_LEVEL=${PHP_LOG_LEVEL:-"notice"}
  PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-"128M"}
  PHP_TIMEOUT=${PHP_TIMEOUT:-"180"}
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:-"2G"}
    
### Adjust PHP Runtime Variables
  sed -i -e "s/<APC_SHM_SIZE>/$APC_SHM_SIZE/g" /etc/php7/conf.d/apcu.ini
  sed -i -e "s/<OPCACHE_MEM_SIZE>/$OPCACHE_MEM_SIZE/g" /etc/php7/conf.d/00_opcache.ini
  sed -i -e "s/<PHP_MEMORY_LIMIT>/$PHP_MEMORY_LIMIT/g" /etc/php7/php-fpm.conf
  sed -i -e "s/<PHP_MEMORY_LIMIT>/$PHP_MEMORY_LIMIT/g" /etc/php7/php.ini
  sed -i -e "s/<PHP_TIMEOUT>/$PHP_TIMEOUT/g" /etc/php7/php.ini
  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/php7/php-fpm.conf
  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/php7/php.ini

### Timezone Config
  echo 'date.timezone='`cat /etc/timezone` >> /etc/php7/conf.d/timezone.ini

### SMTP Config
  echo 'sendmail_path="/usr/bin/msmtp -C /etc/msmtp -t "' > /etc/php7/conf.d/smtp.ini

  sed -i -e "s/<PHP_LOG_LEVEL>/$PHP_LOG_LEVEL/g" /etc/php7/php-fpm.conf
 
  mkdir -p /www/logs/php-fpm
  chown -R nginx /www/logs/php-fpm
  
  mkdir -p /tmp/state
  touch /tmp/state/init-20-php-fpm