#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/init-30-freescout ]
do
  sleep 1
done

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
    set -x
fi

if [ ! -f /tmp/state/10-nginx ]; then

	### Force Reset Permissions for Security
	chown -R nginx:www-data /www/html
	mkdir -p /tmp/state
	echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** [freescout] Starting nginx'
exec nginx
