#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
    set -x
fi

if [ ! -f /tmp/state/20-php-fpm ]; then
	### Start php-fpm
	mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/20-php-fpm
fi


echo ''
echo '** [freescout] Starting php-fpm'
exec s6-setuidgid nginx php-fpm7 -F;
